import blogData from "@/data/blog-posts.json";

export interface BlogPost {
  title: string;
  date: string;
  subtitle: string;
  excerpt: string;
  url: string;
  coverImage?: string;
  wordcount?: number;
}

/**
 * Read blog posts from the pre-fetched JSON file.
 * The JSON is generated by `scripts/fetch-blog.mjs` which runs
 * before `next build`. If the Substack API is unreachable during CI,
 * the committed fallback JSON is used instead.
 */
export async function fetchBlogPosts(): Promise<BlogPost[]> {
  return (blogData as BlogPost[]).map((post) => ({
    ...post,
    coverImage: post.coverImage || undefined,
    wordcount: post.wordcount || undefined,
  }));
}
