export const PUBLICATIONS_A = [
{
    title: "Stage-dependent scaling of travel distance shaped by 3D urban form",
    authors: "Yangzi Che, Guangdong Li, Xiaoping Liu, Libang Ma, Kangning Huang",
    venue: "submitted to PNAS",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: true,
    highlights: [
      "Applies a floor-area-weighted 3D mobility-distance metric to 6,582 cities and over 650 million buildings across 173 countries, showing that vertical urban structure can either compress or stretch inferred mobility space",
      "Finds 3D mobility distances are smaller than 2D estimates in 79% of cities due to vertical intensification, but rapidly urbanizing megacities such as Shanghai and New Delhi exhibit 'volumetric sprawl' where vertical growth exceeds 2D estimates by 9–12%",
      "Identifies stage-dependent scaling breakpoints at ~2.7 million residents and ~$12,476 per capita, beyond which the mobility-distance scaling exponent declines from 0.52 to 0.36, marking a transition toward more efficient urban organization",
      "Shows that the mitigation potential of vertical urban form is strongest during early-to-mid development, with marginal gains diminishing in high-income large cities where volumetric distribution and spatial organization become the primary determinants of mobility efficiency",
    ],
    keywords: ["3D urban form", "urban scaling", "mobility distance", "transport energy", "sustainable urbanization", "vertical urban growth", "volumetric sprawl"],
  },
{
    title: "Projecting global urban land expansion and heat island intensification through 2050",
    authors: "Kangning Huang, Xia Li, Xiaoping Liu, Karen C. Seto",
    venue: "Environmental Research Letters",
    year: 2019,
    citationCount: 466,
    doi: "10.1088/1748-9326/ab4b71",
    isLeadAuthor: true,
    webUrl: "https://kangning-huang.github.io/main/urban-expansion",
    highlights: [
      "Projects global urban land areas to expand by 0.6–1.3 million km² (78%–171%) between 2015 and 2050 under shared socioeconomic pathways (SSPs)",
      "Estimates urban heat island intensification of 0.5–0.7 °C on average, with localized warming reaching up to 3 °C due to urban land-cover change",
      "Finds that urban expansion-driven warming can be about half, and in some locations up to two times, as strong as greenhouse gas-induced warming under RCP 4.5",
      "Identifies tropical regions in the Southern Hemisphere as facing disproportionately high extreme heat risk from compounding urbanization and climate warming",
      "Combines spatially explicit urban expansion modeling at 5-km resolution with mathematical urban heat island models across roughly half of the world's future urban population",
    ],
    keywords: ["urban expansion", "urban heat island", "SSP scenarios", "global urbanization projections", "land-use change modeling", "WRF climate model", "urban land cover 2050"],
  },
{
    title: "An improved artificial immune system for seeking the Pareto front of land-use allocation problem in large areas",
    authors: "Kangning Huang, Xiaoping Liu, Xia Li, Jiayong Liang, Shenjing He",
    venue: "International Journal of Geographical Information Science",
    year: 2013,
    citationCount: 106,
    doi: "10.1080/13658816.2012.730147",
    isLeadAuthor: true,
    highlights: [
      "Proposes AIS-MOLA, an improved artificial immune system for multi-objective land-use allocation that seeks the Pareto front to reveal trade-offs among spatial suitability and compactness objectives",
      "Introduces heuristic hypermutation based on compromise programming, non-dominated neighbour-based proportional cloning, and a crossover operator that preserves connected land-use patches",
      "Outperforms Pareto Simulated Annealing (PSA) by generating solutions closer to the true Pareto front while requiring only 5.1% of PSA's computation time",
      "Validated on a large-area case study in Panyu, Guangdong, China (389 × 337 cells) demonstrating optimal trade-offs between spatial suitability and compactness",
    ],
    keywords: ["land-use optimization", "Pareto front", "artificial immune system", "multi-objective optimization", "spatial planning", "GIScience"],
  },
{
    title: "Persistent increases in nighttime heat stress from urban expansion despite heat island mitigation",
    authors: "Kangning Huang, Xuhui Lee, Brian Stone Jr., Jason Knievel, Michelle L. Bell, Karen C. Seto",
    venue: "Journal of Geophysical Research: Atmospheres",
    year: 2021,
    citationCount: 66,
    doi: "10.1029/2020JD033831",
    isLeadAuthor: true,
    highlights: [
      "Urban expansion through 2050 slightly reduces daytime heat stress (~0.2 °C wet-bulb globe temperature) but intensifies nighttime heat stress by ~1 °C on average and up to 2–3 °C in mega-urban regions of China, India, and Nigeria",
      "Approximately half of the nighttime outdoor urban heat stress increase from urban expansion persists even after large-scale deployment of cool roofs as a heat island mitigation strategy",
      "Uses WRF simulations with spatially explicit urban land expansion projections and wet-bulb globe temperature (WBGT) as a combined temperature-humidity metric to assess physiological heat stress",
      "Demonstrates that infrastructure-based mitigation measures such as cool and green roofs are insufficient alone, highlighting the need for complementary adaptation strategies to address persistent nighttime heat stress",
    ],
    keywords: ["nighttime heat stress", "urban heat island mitigation", "urban expansion", "WRF simulation", "nocturnal heat exposure", "climate and health"],
  },
{
    title: "Facilitating urban climate forecasts in rapidly urbanizing regions with land-use change modeling",
    authors: "Kangning Huang, Jiye Leng, Yong Xu, Xinwei Li, Meng Cai, Ran Wang, Chao Ren",
    venue: "Urban Climate",
    year: 2021,
    citationCount: 24,
    isLeadAuthor: true,
    highlights: [
      "Proposes a local climate zone (LCZ) land-use change simulation framework that groups ten urban land types into three categories (high-rise, mid-rise, low-rise) for more reliable urbanization simulation",
      "Shows that the spatial pattern of occurrence probabilities of grouped urban land types aligns with the economic land price bid curve, linking urban morphology transitions to land market dynamics",
      "Validated in the Pearl River Delta metropolitan area, demonstrating applicability to rapidly urbanizing coastal regions where frequent transitions among urban land types alter climate-relevant surface properties",
      "Addresses a critical gap in urban climate forecasting by coupling LCZ-based land-use change modeling with meteorological simulation for scenario-based warming projections",
    ],
    keywords: ["urban climate forecast", "land-use change modeling", "Pearl River Delta", "Greater Bay Area", "rapid urbanization", "SLEUTH model"],
  },
{
    title: "Urban forests facing climate risks",
    authors: "Kangning Huang",
    venue: "Nature Climate Change",
    year: 2022,
    citationCount: 17,
    isLeadAuthor: true,
    highlights: [
      "News & Views commentary in Nature Climate Change highlighting that more than two-thirds of urban tree species worldwide are projected to face climate risk by 2050",
      "Discusses a global assessment of 3,129 species across 164 cities showing cities at low latitudes face the greatest vulnerability, with nearly all urban tree species exceeding climatic safety margins",
      "Argues that urban forests are central to climate adaptation and nature-based solutions, yet species selection for urban greening rarely accounts for future climatic conditions",
      "Calls for proactive strategies including planting climate-resilient species and adaptive management to sustain the ecological, economic, and public health benefits of urban trees",
    ],
    keywords: ["urban forests", "urban trees climate change", "urban canopy", "nature-based solutions", "climate adaptation", "urban cooling"],
  },
{
    title: "Declining urban density attenuates rising population exposure to surface heat extremes",
    authors: "Kangning Huang, Brian Stone Jr., ChengHe Guan, Jiayong Liang",
    venue: "Scientific Reports",
    year: 2025,
    citationCount: 3,
    doi: "10.1038/s41598-025-96045-z",
    isLeadAuthor: true,
    highlights: [
      "Across the 1,000 largest global cities (2003–2020), declining urban population density attenuates the rise in population-weighted surface urban heat island extremes by approximately 0.5 K per decade per 1,000 persons/km²/year decrease in density",
      "Cities undergoing densification face disproportionately greater increases in population-weighted exposure to surface heat extremes compared to area-average trends",
      "Vegetation changes show a moderate association with population-weighted heat exposure (R² = 0.56), while variations in surface albedo exhibit a negligible relationship (R² = 0.03)",
      "Highlights the need for strategic urban planning that balances compact development co-benefits against amplified heat exposure risks in rapidly densifying cities",
    ],
    keywords: ["urban density", "heat exposure", "surface urban heat island", "urban sprawl", "climate equity", "satellite land-surface temperature"],
  },
{
    title: "Nested economies of scale in global city mass",
    authors: "Kangning Huang, Mingzhen Lu",
    venue: "Nature Cities (accepted)",
    year: 2026,
    citationCount: 0,
    url: "https://arxiv.org/abs/2507.03960",
    isLeadAuthor: true,
    webUrl: "https://city-mass.nested-complexity.net",
    highlights: [
      "Analyzes over 3,000 cities globally to reveal universal sub-linear scaling of built mass with population, with a city-level scaling exponent of β ≈ 0.90 meaning larger cities use less built mass per capita",
      "Finds that neighborhood-level scaling exhibits an even smaller exponent (δ ≈ 0.75) than city-level scaling (β ≈ 0.90), demonstrating that economies of scale in built mass intensify at finer spatial resolutions",
      "Proposes a theoretical framework showing that city-level sub-linear scaling emerges from the aggregation of within-city neighborhood-level disparities, establishing a nested multi-scale scaling relationship",
      "Redefines 'over-built' and 'under-built' conditions as deviations from expected scaling patterns, linking excess built mass to environmental impact and deficient built mass to inadequate living standards",
    ],
    keywords: ["urban scaling laws", "Zipf's law", "city size distribution", "built mass", "urban allometry", "urban economics"],
  },
{
    title: "Spatially resolved global potential for year-round solar-powered artificial intelligence computing",
    authors: "Yimin Chen, Jing Qian, Yijing Wang, Xiaoping Liu, Ming Luo, Yutian Liang, Weilin Liao, Zhu Deng, Kangning Huang",
    venue: "submitted to PNAS",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: true,
    highlights: [
      "Maps near-term global opportunities for solar-powered hyperscale data centres by integrating monthly photovoltaic yield, climate-driven cooling efficiency, suitable land, high-voltage infrastructure, and digital-network accessibility",
      "Identifies 6,290 sites worldwide that meet the year-round monthly energy requirement of a 100-MW IT load, an upper-bound threshold-equivalent load of ~714 GW",
      "Finds the United States alone holds about 34% of this solar-powered computing potential",
      "Shows countries with high potential but weak geopolitical alignment toward China hold 46% of the global total, versus 28% for strongly aligned countries — exposing unequal exposure to renewable-hardware procurement constraints given China's dominance in PV and battery manufacturing",
      "Concludes that climate and infrastructure define the physical geography of green AI, while geopolitics may condition whether the potential is realized",
    ],
    keywords: ["green AI", "data centers", "solar power", "photovoltaic energy", "renewable energy", "geopolitics", "hyperscale computing", "energy geography", "AI electricity demand"],
  },
{
    title: "Rapid Probabilistic Inundation Mapping Using Local Thresholds and Sentinel-1 SAR Data on Google Earth Engine",
    authors: "Jiayong Liang, Desheng Liu, Lihan Feng, Kangning Huang",
    venue: "Remote Sensing",
    year: 2025,
    citationCount: 1,
    doi: "10.3390/rs17101747",
    isLeadAuthor: true,
    highlights: [
      "Implements a probabilistic inundation mapping method on Google Earth Engine using Sentinel-1 SAR data and land-cover-specific local thresholds derived from fitted Gamma distributions",
      "Achieves strong accuracy with Brier Scores of 0.05–0.07, Logarithmic Loss of 0.1–0.2, and Expected Calibration Error of 0.03–0.04 across flood events on five continents",
      "Produces pixel-level inundation probability estimates rather than binary classification, enabling uncertainty quantification in flood mapping",
      "Enables rapid, scalable flood mapping through Google Earth Engine with user-refinable local thresholds for operational disaster response across diverse geographic settings",
    ],
    keywords: ["flood mapping", "Sentinel-1 SAR", "Google Earth Engine", "inundation detection", "remote sensing", "probabilistic mapping"],
  },
{
    title: "Unveiling the causal link between informal settlement demolition and urban cooling",
    authors: "Yujie Sun, Xuyan Gao, Jiayong Liang, Kangning Huang",
    venue: "npj Environmental Social Sciences",
    year: 2026,
    citationCount: 0,
    doi: "10.1038/s44432-026-00009-1",
    isLeadAuthor: true,
    webUrl: "https://kangning-huang.github.io/urban-renewal-cooling-DID/",
    highlights: [
      "Applies a difference-in-differences causal framework to 77 demolished informal settlements and 584 control sites across Beijing, Shanghai, and Guangzhou (2002–2022), establishing a clear causal cooling signal of approximately 1.5 K",
      "Shows that post-demolition cooling depends on subsequent land use, with greening standards and lower floor-area ratios reinforcing temperature reduction",
      "Finds the cooling effect varies by climate context, with stronger thermal benefits in drier cities like Beijing compared to more humid cities",
      "Notes the total demolished area across the three cities is only approximately 7.7 km², cautioning that surface temperature reductions cannot be directly equated with health benefits",
    ],
    keywords: ["informal settlements", "urban renewal", "urban cooling", "difference-in-differences", "causal inference", "slum demolition", "Global South"],
  },
{
    title: "Height-Aware and Protection-Informed Flood Assessment Shifts Global Urban Risk Distribution",
    authors: "Jiayong Liang, Imman Hilaly, Xuyan Gao, ChengHe Guan, Ying Li, Kangning Huang",
    venue: "Scientific Reports (accepted)",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: true,
    preprint: "https://www.researchsquare.com/article/rs-6900146/v1",
    webUrl: "https://kangning-huang.github.io/3D-urban-flood-risk/",
    highlights: [
      "Integrating building height and protection standards shifts the global flood damage distribution: Southeast Asia accounts for 42% of damages versus only 15% under conventional flood-depth-only assessments",
      "Sole reliance on flood depth overestimates risk in regions with resilient vertical urban forms and robust protection (e.g., Europe, East Asia) while underestimating it in areas with low-rise, unprotected development",
      "Chinese cities show strong dependence on protection systems that can reduce potential flood damages by over 90%, as illustrated by Wuhan where damages drop to 0.12%–0.17% after accounting for its 100-year protection standard",
      "Countries such as Vietnam, Cambodia, Bangladesh, Thailand, and Pakistan show high vulnerability, with more than 30% of building footprints located within floodplains",
    ],
    keywords: ["urban flood risk", "3D flood assessment", "building height", "flood protection standards", "climate risk", "global flood modeling"],
  },
{
    title: "Planning for rhythmized urban parks: Temporal park classification and modes of action",
    authors: "Xiyuan Ren, ChengHe Guan, Shengze Chen, Meizi You, Ying Li, Kangning Huang",
    venue: "Journal of the American Planning Association",
    year: 2026,
    citationCount: 2,
    doi: "10.1080/01944363.2025.2523604",
    isLeadAuthor: true,
    highlights: [
      "Uses 1.5 million mobile phone records from 254 urban parks in Tokyo to classify parks by temporal visitation rhythms across daily, weekly, and seasonal scales, challenging traditional static size-based park classification",
      "Reveals that park visitation patterns are shaped by user preference variation and accessibility barriers, with parks rhythmized by seasonal events and daily routines such as commuting and exercise",
      "Proposes four modes of action for temporal park planning: year-round activity tracing, temporary and tactical designs, inclusive park systems for spatiotemporal equity, and public engagement cultivating a sense of time and identity",
      "Demonstrates how temporal insights inform targeted design interventions, such as fitness infrastructure for morning-popular neighborhood parks and extended operating hours for long-evening central parks",
    ],
    keywords: ["urban parks", "park planning", "temporal classification", "urban recreation", "public space design", "urban planning"],
  },
{
    title: "Unequal Effects of the Lockdown on Mental Health in Shanghai: The Moderating and Mediating Role of Neighborhood Environment and Online Social Connections",
    authors: "Yaolin Pei, Xiang Qi, Gen Li, Weiming Tang, Kangning Huang, Brian J. Hall, Bei Wu",
    venue: "Journal of Community Psychology",
    year: 2025,
    citationCount: 2,
    isLeadAuthor: false,
    highlights: [
      "Among 3,763 Shanghai residents surveyed during the 2022 COVID-19 lockdown, lower socioeconomic status was significantly associated with higher depressive symptoms and anxiety (B = 0.173 and B = 0.147, p < 0.001)",
      "Neighborhood social capital, community management quality, and frequency of online social connections via WeChat partially mediated the association between socioeconomic status and mental health outcomes",
      "Neighborhood social capital and online social connections also moderated SES-driven mental health inequalities, mitigating the disparity in depressive symptoms and anxiety among lower-SES residents",
    ],
    keywords: ["COVID-19 lockdown", "mental health", "Shanghai", "neighborhood environment", "social connections", "health equity"],
  },
{
    title: "Short-Term Effect of Air Pollution on Daily Hospital Visits for Anxiety Disorders in Southern China",
    authors: "Xinyuan Zhong, Tingting Guo, Jianghui Zhang, Qiong Wang, Rong Yin, Kunpeng Wu, Qing Zou, Meng Zheng, Brian J. Hall, Andre M. N. Renzaho, Kangning Huang, Wen Chen",
    venue: "Toxics",
    year: 2025,
    citationCount: 4,
    doi: "10.3390/toxics13010045",
    isLeadAuthor: false,
    highlights: [
      "Short-term exposure to all six ambient air pollutants (PM2.5, PM10, NO2, CO, SO2, O3) was significantly associated with increased daily hospital visits for anxiety disorders in Qingyuan, Guangdong Province, even at concentrations below China's and WHO's standards",
      "NO2 showed the strongest association (OR = 1.19, 95% CI: 1.05–1.34 per IQR increase at lag 0–7 days), followed by CO (OR = 1.14 at lag 0–2 days), with robust results across sensitivity analyses",
      "Subgroup analyses revealed that females and middle-aged individuals were more susceptible to air-pollution-related anxiety disorder hospital visits than males and other age groups",
    ],
    keywords: ["air pollution", "anxiety disorders", "PM2.5", "hospital visits", "environmental health", "southern China"],
  },
{
    title: "Measuring rising heat and flood risk along the belt-and-road initiative",
    authors: "Jiayong Liang, Maria Adele Carrai, Ammar A. Malik, Xi Gao, Xuyan Gao, Lihan Feng, Kangning Huang",
    venue: "Discover Environment",
    year: 2024,
    citationCount: 1,
    isLeadAuthor: true,
    highlights: [
      "Under SSP3-7.0, labor workability across 217 BRI projects in 70 countries could decrease by 31% by end of century, three times the 10% decline under SSP1-2.6, due to rising wet bulb globe temperatures",
      "Under SSP2-4.5, floods with a historical 10-year return period are projected to occur every 5 years at BRI project sites, effectively doubling flood frequency",
      "Regional flood risk varies substantially, with 100-year floods projected to recur every 15 years in South Asia and every 24 years in Sub-Saharan Africa",
      "These largely overlooked climate risks threaten the commercial viability and loan repayment capacity of BRI infrastructure projects collectively valued at an estimated $1 trillion",
    ],
    keywords: ["Belt and Road Initiative", "climate risk", "heat risk", "flood risk", "infrastructure", "international development"],
  },
{
    title: "Mega-city development impact on hourly extreme rainfall over the South China Greater Bay Area under near-future climate warming",
    authors: "Chenxi Hu, Chi-Yung Tam, Xinwei Li, Kangning Huang, Chao Ren, Kwun Yip Fung, Ziqian Wang",
    venue: "Urban Climate",
    year: 2023,
    citationCount: 21,
    isLeadAuthor: false,
    highlights: [
      "Convection-permitting WRF simulations coupled with an Urban Canopy Model show that both mega-city development and near-future warming independently enhance the frequency and intensity of hourly extreme rainfall over the Greater Bay Area",
      "Urban expansion has a comparable effect on local extreme rainfall as near-future (2001–2050) climate warming, nearly doubling the frequency of very heavy rainfall events exceeding 90 mm/hr over urban areas",
      "Observational records from 1971 to 2016 confirm that both intensity and frequency of extreme rainfall increased by more than 5% per decade across most Greater Bay Area mega-cities, concurrent with rapid urban expansion",
    ],
    keywords: ["extreme rainfall", "mega-city development", "Greater Bay Area", "WRF modeling", "urban precipitation", "climate warming"],
  },
{
    title: "Investigating future urbanization's impact on local climate under different climate change scenarios in MEGA-urban regions: A case study of the Pearl River Delta, China",
    authors: "Pak Shing Yeung, Jimmy Chi-Hung Fung, Chao Ren, Yong Xu, Kangning Huang, Jiye Leng, Michael Mau-Fong Wong",
    venue: "Atmosphere",
    year: 2020,
    citationCount: 26,
    isLeadAuthor: false,
    highlights: [
      "Couples urban growth projections with WRF regional climate modeling to quantify future urbanization impacts on local climate in the Pearl River Delta mega-urban region",
      "Shows that urban expansion substantially modifies local temperature and precipitation patterns beyond background climate change under multiple RCP scenarios",
      "Finds that future land-use change contributes an additional warming signal comparable in magnitude to the urban heat island effect under current conditions",
    ],
    keywords: ["Pearl River Delta", "urbanization impact", "climate scenarios", "regional climate modeling", "land-use change", "mega-urban region"],
  },
{
    title: "Toward Cooler Cities by Homogeneous Scale Planning",
    authors: "Xucai Zhang, Xiaobing Wei, Xiaoping Liu, Honghong Wei, Yue Zheng, Hongkai Gu, Yangzi Che, Yeran Sun, Ming Luo, Weilin Liao, Haosheng Huang, Kangning Huang",
    venue: "in revision at PNAS",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: false,
    highlights: [
      "Introduces the Urban Homogeneous Scale (UHS) metric — the spatial scale of functionally homogeneous building clusters — as a novel urban morphology measure for understanding urban heat island effects",
      "Analyzes 232,874 observations across 101 global cities using machine learning (XGBoost) building classification and Double Machine Learning causal inference to establish UHS-heat relationships",
      "Finds that a 100-metre increase in UHS leads to approximately 5% decrease in daytime urban heat island intensity, with daytime cooling more pronounced in inland, humid, and high-income regions",
      "Proposes homogeneous scale planning as a land-use strategy for mitigating urban heat, with implications for mixed-use zoning and urban design guidelines",
    ],
    keywords: ["urban heat island", "Urban Homogeneous Scale", "urban morphology", "climate adaptation", "urban planning", "causal inference", "machine learning"],
  },
{
    title: "Material-saving strategies for decarbonizing the global urban building stock",
    authors: "Yupeng Liu, Kangning Huang, Shengping Li, Karen C. Seto, Wei-Qiang Chen",
    venue: "submitted to Nature Communications",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: false,
    highlights: [
      "Evaluates material-saving strategies — including material efficiency, lightweighting, and longer building lifetimes — as levers for decarbonizing the global building stock",
      "Links reductions in construction-material demand to lower embodied carbon emissions across the world's buildings",
      "Offers a global-scale perspective on how dematerialization can complement energy and fuel measures in building-sector climate mitigation",
    ],
    keywords: ["building stock", "material efficiency", "decarbonization", "embodied carbon", "construction materials", "climate mitigation", "dematerialization"],
  },
{
    title: "Infrastructure reach and capacity pressure in sub-Saharan Africa's future urban expansion",
    authors: "Kangning Huang, Yimin Chen",
    venue: "submitted to Nature Communications",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: false,
    highlights: [
      "Examines the mismatch between infrastructure reach and capacity pressures driven by rapid urban expansion across sub-Saharan Africa",
    ],
    keywords: ["sub-Saharan Africa", "urban expansion", "infrastructure", "urban growth", "development", "Nature Communications"],
  },
];
