export const PUBLICATIONS_B = [
{
    title: "Global multi-city heat perception: seasonal dynamics and climate–health signals",
    authors: "Meizi You, ChengHe Guan, Yuming Guo, Bao-Jie He, Steven Jige Quan, John S. Ji, Jianxiang Huang, Rongbin Xu, Zhihu Xu, Tianren Yang, Longxu Yan, Kangning Huang, ... Waishan Qiu",
    venue: "under review at Nature Communications",
    year: 2026,
    citationCount: 0,
    isLeadAuthor: false,
    highlights: [
      "Applies a fine-tuned BERT-based language model to 278 million geotagged social media posts to quantify how people perceive and express heat across 347 cities in 50 countries",
      "Finds that heat perception extends well beyond summer: 35.4% of cities sustain multi-season perception peaks and 16.1% show counter-seasonal regimes where winter perception surpasses summer",
      "Shows spatial concentration of heat perception follows continent-specific modes — intensity-driven in Africa and variability-driven in South America",
      "Demonstrates that co-occurring extreme temperature and elevated perception yields the strongest health associations, especially for adults aged ≥70 (mortality RR = 1.479) and respiratory mortality (RR = 1.826)",
      "Establishes expressed heat perception as a scalable, season-resolved signal that complements temperature and identifies when heat becomes socially salient",
    ],
    keywords: ["heat perception", "urban heat", "climate and health", "social media", "large language model", "BERT", "climate adaptation", "heat mortality"],
  },
{
    title: "Global projections of future urban land expansion under shared socioeconomic pathways",
    authors: "Guangzhao Chen, Xia Li, Xiaoping Liu, Yimin Chen, Xun Liang, Jiye Leng, Xiaocong Xu, Wenjie Liao, Yue'an Qiu, Qianlian Wu, Kangning Huang",
    venue: "Nature Communications",
    year: 2020,
    citationCount: 937,
    doi: "10.1038/s41467-020-14386-x",
    isLeadAuthor: false,
    highlights: [
      "Projects global urban land expansion through 2100 under all five SSPs, with SSP5 yielding the greatest total urban land area and SSP1/SSP4 showing turning points in the 2080s/2070s as socioeconomic growth slows",
      "Approximately 50–63% of newly expanded urban land worldwide is projected to replace existing croplands, making agricultural land the dominant land-cover type lost to urbanization",
      "The resulting cropland loss is estimated to reduce global crop production by 1–4%, equivalent to the annual food requirements of 122 to 1,389 million people depending on the SSP scenario",
      "China and the United States face the largest urban expansion under SSP5, whereas Latin American regions experience greater expansion under SSP3, reflecting regionally distinct urbanization pressures",
    ],
    keywords: ["global urban expansion", "SSP scenarios", "urban land projections", "Nature Communications", "IPCC", "urban growth 2100"],
  },
{
    title: "High-spatiotemporal-resolution mapping of global urban change from 1985 to 2015",
    authors: "Xiaoping Liu, Yinghuai Huang, Xiaocong Xu, Xuecao Li, Xia Li, Philippe Ciais, ... Kangning Huang, ... Zhenzhong Zeng",
    venue: "Nature Sustainability",
    year: 2020,
    citationCount: 843,
    doi: "10.1038/s41893-020-0521-x",
    isLeadAuthor: false,
    highlights: [
      "Produces annual maps of global urban land at 30-meter resolution from 1985 to 2015, revealing an 80% increase in the world's urban footprint from approximately 362,000 km² to 653,000 km²",
      "China and the United States together accounted for nearly half of the global net increase in urban land, with China's urban area expanding more than fourfold during the study period",
      "Global urban expansion disproportionately consumed cropland, with approximately 300,000 km² of agricultural land converted to urban uses, raising food security concerns",
      "The rate of global urbanization accelerated markedly after 2000, with developing countries in Asia and Africa driving the fastest urban growth",
    ],
    keywords: ["global urban change", "Landsat", "remote sensing", "urban land cover", "GAIA dataset", "impervious surface mapping", "30-meter resolution"],
  },
{
    title: "Research gaps in knowledge of the impact of urban growth on biodiversity",
    authors: "Robert I. McDonald, Andressa V. Mansur, Fernando Ascensão, ... Kangning Huang, ... Carly Ziter",
    venue: "Nature Sustainability",
    year: 2020,
    citationCount: 637,
    doi: "10.1038/s41893-019-0436-6",
    isLeadAuthor: false,
    highlights: [
      "Projects that urban expansion will convert approximately 290,000 km² of natural habitat to urban land uses between 2000 and 2030, with the most severe losses in tropical coastal regions of China, Brazil, and Nigeria",
      "A systematic review of 922 studies found that 72% of research on direct urban impacts on biodiversity was conducted in high-income countries, despite the greatest projected habitat loss occurring in lower-income countries",
      "Indirect urban impacts on biodiversity, such as food consumption and resource demand, affect a far greater land area than direct habitat conversion, yet only 34% of reviewed studies quantified these indirect effects",
      "By 2030, urban areas will accommodate over 1.2 billion additional people globally, yet critical research gaps persist in tropical and Southern Hemisphere regions where urbanization-driven biodiversity loss is expected to be most severe",
    ],
    keywords: ["urban biodiversity", "habitat loss", "urban ecology", "conservation planning", "biodiversity hotspots", "urban growth impact"],
  },
{
    title: "A multi-type ant colony optimization (MACO) method for optimal land use allocation in large areas",
    authors: "Xiaoping Liu, Xia Li, Xun Shi, Kangning Huang, Yilun Liu",
    venue: "International Journal of Geographical Information Science",
    year: 2012,
    citationCount: 167,
    doi: "10.1080/13658816.2011.635594",
    isLeadAuthor: false,
    highlights: [
      "Proposes the MACO method, assigning different ant types to different land uses, outperforming simulated annealing by ~4.5% and genetic algorithms by ~1.3% in overall land-use allocation utility",
      "Generates more spatially compact land-use patterns than competing methods, improving compactness over SA and GA by 8.9% and 1.7% respectively with significantly less computation time",
      "Addresses the exponentially growing solution space of large-area land-use allocation by incorporating spatial exchange mechanisms and optimizing across suitability, compactness, and conversion cost objectives",
    ],
    keywords: ["ant colony optimization", "land-use allocation", "spatial optimization", "multi-objective planning", "GIScience"],
  },
{
    title: "Fugitive Road Dust PM2.5 Emissions and Their Potential Health Impacts",
    authors: "Siyu Chen, Xiaorui Zhang, Jintai Lin, Jianping Huang, Dan Zhao, Tiangang Yuan, Kangning Huang, ... Li Xie",
    venue: "Environmental Science & Technology",
    year: 2019,
    citationCount: 150,
    doi: "10.1021/acs.est.9b00666",
    isLeadAuthor: false,
    highlights: [
      "Fugitive road dust PM2.5 emissions in urban Lanzhou were approximately 1,141 kg per day, accounting for 24.6% of total PM2.5 emissions, concentrated in areas of intense traffic and construction",
      "Constructs a high-resolution (500 × 500 m) road dust PM2.5 emissions inventory, finding emissions exceeding 30,000 µg/m²/day in areas with smaller particle sizes and higher traffic intensity",
      "Estimates 234.5 premature deaths attributable to road dust PM2.5 exposure in Lanzhou in 2017, underscoring that reducing road dust emissions is critical for public health in developing urban regions",
    ],
    keywords: ["PM2.5", "road dust emissions", "air pollution", "urban air quality", "health impacts", "particulate matter"],
  },
{
    title: "Automatic registration of multisensor images using an integrated spatial and mutual information (SMI) metric",
    authors: "Jiayong Liang, Xiaoping Liu, Kangning Huang, Xia Li, Dagang Wang, Xianwei Wang",
    venue: "IEEE Transactions on Geoscience and Remote Sensing",
    year: 2013,
    citationCount: 110,
    doi: "10.1109/tgrs.2013.2242895",
    isLeadAuthor: false,
    highlights: [
      "Introduces a novel SMI metric integrating spatial information from detected features with mutual information between reference and sensed images, achieving more robust registration than either metric alone",
      "Employs a two-phase searching strategy using ant colony optimization for continuous domains, first identifying approximate solutions via spatial information then refining with the combined SMI metric",
      "Demonstrates highly accurate automatic registration on multi-sensor remote sensing imagery (TM, SPOT, SAR) where conventional single-metric methods fail",
    ],
    keywords: ["image registration", "multi-sensor", "mutual information", "remote sensing", "SAR", "IEEE TGRS"],
  },
{
    title: "Quantifying contributions of natural and anthropogenic dust emission from different climatic regions",
    authors: "Siyu Chen, Nanxuan Jiang, Jianping Huang, ... Kangning Huang, ... Taichen Feng",
    venue: "Atmospheric Environment",
    year: 2018,
    citationCount: 104,
    doi: "10.1016/j.atmosenv.2018.07.043",
    isLeadAuthor: false,
    highlights: [
      "Natural dust sources contribute 81.0% of global dust emissions while anthropogenic sources contribute 19.0%, with natural emissions concentrated in hyper-arid regions and anthropogenic emissions in semi-arid and sub-humid regions",
      "Semi-arid regions exhibit the most complex interplay, accounting for 42.99% of global anthropogenic dust emissions due to diverse land cover types including grasslands, croplands, and urban areas",
      "The complex mix of natural and anthropogenic dust in semi-arid regions may be a crucial factor enhancing the observed warming trend over these areas under global climate change",
    ],
    keywords: ["dust emissions", "anthropogenic dust", "natural dust", "climate regions", "air quality", "atmospheric environment"],
  },
{
    title: "High-resolution gridded population projections for China under the shared socioeconomic pathways",
    authors: "Yimin Chen, Xia Li, Kangning Huang, Ming Luo, Minyi Gao",
    venue: "Earth's Future",
    year: 2020,
    citationCount: 77,
    isLeadAuthor: false,
    highlights: [
      "Produces 100-meter resolution gridded population projections for China under the SSPs using machine learning, revealing that 30–43% of population in existing coarse-resolution SSP grids is misallocated to non-urban land",
      "Projects that exposure to extreme heat in China will increase by 121–136% under RCP4.5 and 164–191% under RCP8.5 from 2015 to 2050, concentrated in high-density urbanized areas like the Yangtze and Pearl River Deltas",
      "All scenarios project accelerated population decline in China from 2020 to 2050, though provincial-level trends diverge significantly from the national trajectory",
    ],
    keywords: ["population projections", "China", "SSP scenarios", "gridded population", "urbanization", "climate impact assessment"],
  },
{
    title: "Evaluation of historical and future wetland degradation using remote sensing imagery and land use modeling",
    authors: "Tango Hu, Jiahong Liu, Gang Zheng, Dengrong Zhang, Kangning Huang",
    venue: "Land Degradation & Development",
    year: 2019,
    citationCount: 70,
    isLeadAuthor: false,
    highlights: [
      "Natural wetlands in Hangzhou Bay decreased at ~10 km² per year from 1984 to 2016, with the degradation rate quadrupling from ~4 to ~18 km²/year after establishment of an economic development zone in 2001",
      "Under a continued high-development scenario, the coastline is projected to move approximately 5.89 km inland, undermining coastal protections against sea level rise",
      "Wetland protection scenarios could mitigate projected degradation by approximately 20%, demonstrating that land-use simulation models can identify effective conservation strategies under rapid urbanization",
    ],
    keywords: ["wetland degradation", "remote sensing", "land-use modeling", "habitat loss", "conservation", "land cover change"],
  },
{
    title: "Globally elevated greenhouse gas emissions from polluted urban rivers",
    authors: "Wenhao Xu, Gongqin Wang, Shaoda Liu, ... Kangning Huang, ... Xinghui Xia",
    venue: "Nature Sustainability",
    year: 2024,
    citationCount: 69,
    isLeadAuthor: false,
    highlights: [
      "Global urban rivers emit an estimated 78.1 ± 3.5 Tg CO₂-equivalent annually, with GHG emissions per unit area nearly double those from non-urban rivers (~815 vs ~414 mmol CO₂-eq/m²/day)",
      "Elevated CH₄ and N₂O emissions are driven by widespread eutrophication and altered carbon and nutrient cycling, with the highest emissions in lower-middle-income countries where pollution control is deficient",
      "Highlights that pollution control in urban rivers is an underappreciated but important pathway for reducing urban greenhouse gas emissions, particularly in developing nations",
    ],
    keywords: ["urban rivers", "greenhouse gas emissions", "water pollution", "urban waterways", "climate mitigation"],
  },
{
    title: "Improved snow depth retrieval by integrating microwave brightness temperature and visible/infrared reflectance",
    authors: "Jiayong Liang, Xiaoping Liu, Kangning Huang, Xia Li, Xun Shi, Yaning Chen, Jun Li",
    venue: "Remote Sensing of Environment",
    year: 2015,
    citationCount: 64,
    doi: "10.1016/j.rse.2015.06.016",
    isLeadAuthor: false,
    highlights: [
      "Develops a snow depth retrieval algorithm based on support vector regression that combines passive microwave brightness temperature with visible/infrared reflectance to improve accuracy over microwave-only approaches",
      "Visible and near-infrared measurements contain supplementary information about surface snowpack properties that, when integrated with 19 and 37 GHz data from SSM/I and SSMI/S sensors, significantly reduce retrieval uncertainties",
      "Validated in Xinjiang, China, demonstrating that combining data modalities captures snow cover characteristics more comprehensively than single-sensor retrieval methods",
    ],
    keywords: ["snow depth retrieval", "microwave remote sensing", "data fusion", "visible/infrared reflectance", "cryosphere", "remote sensing"],
  },
{
    title: "Enhancing Climate-Driven Urban Tree Cooling with Targeted Nonclimatic Interventions",
    authors: "Zhaowu Yu, Siheng Li, Wenjun Yang, ... Kangning Huang, ... Weiqi Zhou",
    venue: "Environmental Science & Technology",
    year: 2025,
    citationCount: 29,
    doi: "10.1021/acs.est.4c14275",
    isLeadAuthor: false,
    highlights: [
      "For every 10% increase in urban tree cover, surface temperatures are reduced by 0.25 °C during the day and 0.04 °C at night, with trees in humid regions showing highest daytime cooling and arid zones the greatest nighttime cooling",
      "While climatic factors contribute nearly twice as much to tree cooling efficiency as nonclimatic factors, the nonlinear effects of nonclimatic variables such as impervious surface coverage offer actionable optimization thresholds",
      "Optimal impervious surface coverage for maximizing tree cooling is approximately 60% in arid regions and 40% in humid areas, providing practical guidance for climate-resilient nature-based urban cooling",
    ],
    keywords: ["urban tree cooling", "green infrastructure", "urban canopy management", "nature-based cooling", "urban forestry"],
  },
{
    title: "Dual impact of global urban overheating on mortality",
    authors: "Shasha Wang, Wenfeng Zhan, Bingbing Zhou, ... Kangning Huang, ... Manchun Li",
    venue: "Nature Climate Change",
    year: 2025,
    citationCount: 27,
    doi: "10.1038/s41558-025-02303-3",
    isLeadAuthor: false,
    highlights: [
      "The urban heat island effect reduces global cold-related mortality by more than fourfold compared to the increase in heat-related mortality it causes, revealing a previously overlooked beneficial health effect during cold seasons",
      "Widely implemented urban cooling strategies such as green infrastructure and reflective roofs can have adverse net effects in high-latitude cities while benefiting some tropical cities, highlighting the need for place-specific approaches",
      "Proposes seasonal adjustments to roof albedo as an actionable strategy to simultaneously reduce both heat-related and cold-related mortality across diverse climate zones",
    ],
    keywords: ["urban heat mortality", "urban overheating", "heat-related deaths", "nighttime heat", "Nature Climate Change", "public health"],
  },
{
    title: "Exacerbated heat stress induced by urban browning in the Global South",
    authors: "Huilin Du, Wenfeng Zhan, Bingbing Zhou, ... Kangning Huang, ... Manchun Li",
    venue: "Nature Cities",
    year: 2025,
    citationCount: 0,
    doi: "10.1038/s44284-024-00184-9",
    isLeadAuthor: false,
    highlights: [
      "Urban moist heat in more than 2,300 Global South cities increased by 0.41 ± 0.01 °C per decade between 2003 and 2020, with urban browning contributing an additional 0.05 °C per decade in affected cities",
      "The loss of urban vegetation in Global South cities compounds warming trends driven by climate change and urbanization, disproportionately affecting vulnerable populations in regions such as Nigeria",
      "Introduces a new dataset for measuring urban moist heating rates, revealing that urban browning is an underrecognized driver of heat stress exacerbation in the developing world",
    ],
    keywords: ["urban browning", "heat stress", "Global South", "vegetation loss", "urban greenness", "Nature Cities"],
  },
{
    title: "Multi-sensor image registration by combining local self-similarity matching and mutual information",
    authors: "Xiaoping Liu, Shuli Chen, Li Zhuo, Jun Li, Kangning Huang",
    venue: "Frontiers of Earth Science",
    year: 2018,
    citationCount: 26,
    isLeadAuthor: false,
    highlights: [
      "Integrates local self-similarity (LSS) descriptors, which capture common internal layout features across sensor types, with mutual information to handle images with both rigid and non-rigid radiometric distortions",
      "Uses a Bayesian probabilistic model for matching LSS feature ensembles, followed by particle swarm optimization to maximize combined self-similarity and mutual information for optimal correspondences",
      "Overcomes limitations of conventional registration algorithms that fail when common underlying visual features between different sensor images are not distinct",
    ],
    keywords: ["image registration", "self-similarity", "multi-sensor", "remote sensing", "mutual information", "feature matching"],
  },
{
    title: "Long-term monitoring and evaluation of land development in a reclamation area under rapid urbanization",
    authors: "Tangao Hu, Jinjin Fan, Hao Hou, Yao Li, Yue Li, Kangning Huang",
    venue: "Land Degradation & Development",
    year: 2021,
    citationCount: 13,
    isLeadAuthor: false,
    highlights: [
      "Monitors the detailed spatiotemporal evolution of land development in the Qiantang New District reclamation area in China, revealing dramatic land-use changes under rapid urbanization pressures",
      "Identifies key historical drivers of land-use change in reclaimed coastal areas where understanding of long-term dynamics has been limited",
      "Provides a framework and insights for sustainable land management planning in rapidly urbanizing coastal reclamation regions",
    ],
    keywords: ["land reclamation", "urbanization", "remote sensing monitoring", "land development", "land-use change"],
  },
{
    title: "Mapping of individual building heights reveals the large gap of urban-rural living spaces in the contiguous US",
    authors: "Yangzi Che, Xuecao Li, Xiaoping Liu, Xiaocong Xu, Kangning Huang, ... Xia Li",
    venue: "The Innovation Geoscience",
    year: 2024,
    citationCount: 10,
    isLeadAuthor: false,
    highlights: [
      "Produces a building-scale height map across the contiguous United States circa 2020, revealing downtown areas average 12.4 m in height — more than double the 5.4 m average in suburban areas",
      "Three-dimensional building volume analysis reveals a significantly larger urban-rural gap in living spaces than two-dimensional footprint analysis alone, highlighting the importance of vertical structure",
      "Urban regions offer more limited per-capita living spaces compared to rural areas, but the higher density reduces inequality in living space distribution within urban settings",
    ],
    keywords: ["building height mapping", "urban-rural gap", "3D urban structure", "built environment", "United States", "remote sensing"],
  },
{
    title: "Moderating AC usage can reduce thermal disparity between indoor and outdoor environments",
    authors: "Hong Wei, Bin Chen, Kangning Huang, Meng Gao, Bin Fan, Tao Zhang, Ying Tu, Bing Xu",
    venue: "Environmental Science & Technology",
    year: 2024,
    citationCount: 6,
    doi: "10.1021/acs.est.4c05618",
    isLeadAuthor: false,
    highlights: [
      "Air conditioning systems can reduce indoor temperatures by up to 18 °C but cause substantial nighttime outdoor warming of 2–2.5 °C in high-density urban neighborhoods, creating a thermal equity problem",
      "Increasing the target indoor AC temperature by just 2 °C can reduce outdoor temperatures by up to 1 °C in high-density areas, while reducing the spatial cooled fraction can cut energy consumption by up to 50%",
      "Uses coupled WRF and building energy modeling in Chongqing to demonstrate that moderate AC usage adjustments and temporal scheduling can balance indoor comfort, outdoor heat mitigation, and energy resilience",
    ],
    keywords: ["air conditioning", "thermal disparity", "waste heat", "urban heat island", "indoor-outdoor temperature", "energy efficiency"],
  },
{
    title: "The implementation and application of geographical simulation and optimization systems (GeoSOS)",
    authors: "Xia Li, Dan Li, Xiaoping Liu, Chunhua Lao, Yihan Zhang, Jinqiang He, Kangning Huang",
    venue: "Acta Scientiarum Natralium Universitatis Sunyatseni",
    year: 2010,
    citationCount: 15,
    isLeadAuthor: false,
    highlights: [
      "Integrates three major computational components — cellular automata (CA), multi-agent systems (MAS), and swarm intelligence (SI) — into the unified GeoSOS platform for process-based geographical modeling",
      "Includes multiple CA algorithms (MCE-CA, Logistic-CA, PCA-CA, ANN-CA, Decision-tree-CA) that automatically derive transition rules through data mining for simulating urban growth and land-use change",
      "Couples simulation models with optimization models, demonstrating more satisfactory modeling results under complex changing environments than either approach alone",
    ],
    keywords: ["GeoSOS", "geographical simulation", "cellular automata", "land-use simulation", "spatial optimization", "urban growth modeling"],
  },
{
    title: "Estimations of anthropogenic dust emissions at global scale from 2007 to 2010",
    authors: "Siyu Chen, Jianping Huang, Nanxuan Jiang, ... Kangning Huang, ... Shujie Liao",
    venue: "Atmospheric Chemistry and Physics Discussions",
    year: 2017,
    citationCount: 5,
    isLeadAuthor: false,
    highlights: [
      "Constructs both indirect and direct anthropogenic dust emission schemes validated against CALIPSO satellite observations, identifying high emission centers in India, eastern China, North America, and Africa",
      "Pasturelands contribute approximately 60% of indirect anthropogenic dust emissions, substantially more than croplands, while urban areas emit more (13.5 µg/m²/s) than rural areas (7.9 µg/m²/s)",
      "Unlike natural dust emissions with strong seasonal variation, indirect anthropogenic dust emissions show minimal seasonal fluctuation, highlighting that human-driven dust is a persistent year-round concern",
    ],
    keywords: ["anthropogenic dust emissions", "global dust", "atmospheric modeling", "air quality", "human-caused dust"],
  },
];
